// next.config.js
module.exports = {
  reactStrictMode: true,
  images: {
    domains: [
      "assets.aceternity.com",
      "aceternity.com",
      "images.unsplash.com",
      "store.storeimages.cdn-apple.com",
      "quicktech.in",
      "encrypted-tbn0.gstatic.com",
      "www.apple.com",
      "images-cdn.ubuy.co.in",
      "i.gadgets360cdn.com",
      "encrypted-tbn0.gstatic.com",
      "cdsassets.apple.com",
      "m.media-amazon.com",
      "telecomtalk.info",
      "images.news18.com",
      "help.apple.com",
      "store-images.s-microsoft.com",
      "i.ytimg.com",
      "www.livemint.com",
      "iplanet.one",
      "letsenhance.io",
      "images.macrumors.com",
      "9to5mac.com",
      "static5.depositphotos.com",
    ],
  },
};
